apiVersion: 1

datasources:
  - name: ClickHouse
    uid: sentinel-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: sentinel
      defaultDatabase: sentinel
    secureJsonData:
      password: sentinel
    editable: false
